### ISSUE TITLE
Autoescaping is switched off

### ISSUE THREAD

**Issue by c1rrus** [frctl/nunjucks-engine#3]
Is there a reason why Nunjucks autoescaping is switched off, rather than leaving it on? It appears to be done on this line: https://github.com/frctl/nunjucks/blob/master/src/adapter.js#L91

I had assumed the usual auto-escaping and this behaviour caught me out. Would it be possible to leave auto-escaping on by default and/or make it configurable?

Maybe something like this:
```js
const nunj = require('@frctl/nunjucks')({
    // filters, globals, extensions...
    autoescape: true
}
```

**Comment by allmarkedup** [comment]
@c1rrus I can't actually remember why this was disabled tbh! But I agree it should be enabled by default and then made configurable. It'd be a breaking change but we are going to release a v2.0 of this adapter shortly so it would make sense to get this change into that release too. I'll try to get something together shortly.

**Comment by allmarkedup** [comment]
@c1rrus I've just opened PR #8 to address this. Hopefully that should resolve things :-)

**Comment by c1rrus** [comment]
Fantastic! Looking forward to the 2.0 release!

**Comment by allmarkedup** [comment]
@c1rrus v2.0.0 has just been published that addresses this issue. Let me know if you run into any issues :-)

**Comment by c1rrus** [comment]
Just tried it and it's working fine. Thanks for that!
